### ISSUE TITLE
No Connection.close() ?

### ISSUE THREAD

**Issue by jipen** [JacobCallahan/Hussh#15]
Hello Jacob,

I didn't see a method to close a Connection: is this planned ?

Best regards.

**Comment by JacobCallahan** [comment]
I was leaving this out initially to see if there would be a desire for an explicit close, since it would just close the session (channels are created/destroyed during an action).
If this is something you'd like to see, I certainly could add it, but I'd also probably add a context manager for Connection and recommend that. Both would be available.

**Comment by jipen** [comment]
As I currently use Fabric, I got used to the Connection.close() method to clean them up (on some servers the number of simultaneous SSH connections is limited).
So, good news and a +1 for the context manager ! 👍

**Comment by JacobCallahan** [comment]
@jipen I've opened #16 to address your request. I'll likely wait until the github action can build against Python 3.13 before I push the new release though. Hopefully that will be soon.

**Comment by JacobCallahan** [comment]
@jipen the latest release has this in

**Comment by JacobCallahan** [comment]
@jipen the latest release has this in
